name: Grafana Alloy
version: "1.19.2"
slug: grafana_alloy
description: Runs Grafana Alloy to collect and forward telemetry via Prometheus remote_write
url: https://github.com/carlba/hassio-addons/tree/main/grafana-alloy
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
options:
  alloy_config: ""
schema:
  alloy_config: "str?"
