# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Fluent Bit Log Forwarder
version: '0.3.8'
slug: fluent_bit_log_forwarder
description:
  Collect Home Assistant Core, Host, Supervisor, and app logs and forward them to Grafana Loki via
  Fluent Bit
url: 'https://github.com/carlba/hassio-addons/tree/main/fluent-bit-log-forwarder'
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
hassio_role: admin
map:
  - type: homeassistant_config
    read_only: true
options:
  loki_host: 'loki'
  loki_port: 3100
  loki_tls: false
  loki_uri: '/loki/api/v1/push'
  loki_tenant_id: ''
  loki_user: ''
  loki_password: ''
  collect_core_log: true
  collect_host_log: true
  collect_supervisor_log: true
  collect_addon_logs: true
  poll_interval_seconds: 15
  logs_timezone: 'UTC'
schema:
  loki_host: 'str'
  loki_port: 'port'
  loki_tls: 'bool'
  loki_uri: 'str'
  loki_tenant_id: 'str?'
  loki_user: 'str?'
  loki_password: 'password?'
  collect_core_log: 'bool'
  collect_host_log: 'bool'
  collect_supervisor_log: 'bool'
  collect_addon_logs: 'bool'
  poll_interval_seconds: 'int(5,300)'
  logs_timezone: 'str'
image: 'ghcr.io/carlba/fluent-bit-log-forwarder'
